
# 数据源
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/community_manage_sys?serverTimezone=GMT%2B8&characterEncoding=utf8&characterSetResults=utf8
    username: root
    password: xqx1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  mvc:
    view:
      prefix: /WEB-INF/
      suffix: .jsp
# 日志配置（开发用）
logging:
  level:
    com:
      longder: DEBUG
# 服务端口
server:
  port: 5188

